/* 実行は maxima --batch=Zeilberger_algo.mac */
/* %iを出さないなら maxima -q < Zeilberger_algo.mac */

load(zeilberger)$

F(a) := binomial(n,k)^2 * binomial(n+k,k)^a;
/* Zeilberger(F(1), k, n)[1][1]; */
Zeilberger(F(1), k, n)[1][2];

F(a) := a^k * binomial(n,k) * binomial(2*n,k);
print("         A387928")$
Zeilberger(F(3), k, n)[1][2];

F(a) := a^(n-k) * binomial(n,k) * binomial(2*n,k);
print("         A387929")$
Zeilberger(F(3), k, n)[1][2];